### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by Wawowo3** [ck-yung/dir2cs#1]
The program cannot work! See below!

~ $ ls -la *.txt
-rw-rw-r-- 1 default7 default7 78 Oct 25  2020 readme.txt
-rw-rw-r-- 1 default7 default7 55 Jan 31  2021 time.txt

~ $ ls -la Documents/*xt
-rw-rw-r-- 1 default7 default7 3116 Oct 16 21:18 Documents/a2.txt

~ $ dir2 -s *xt
  55  2021-01-31 19:35 time.txt
  78  2020-10-25 11:06 readme.txt
 133  2020-10-25 11:06 - 2021-01-31 19:35      2 /home/default7

**Comment by ck-yung** [comment]
To Mac/Linux Users, something is called "Shell Globbing". So command "dir2 -s *xt" is auto changed into "dir2 -s time.txt readme.txt". In the case, please use single-quote or double-quote to enclose wild card. That is:
dir2 -s '*xt'
